/**
 * Conversion & generation API client.
 *
 * Handles two flows:
 * 1. Prompt-based generation: user describes a design → AI generates UI code
 * 2. Object conversion: canvas sketches/images → UI code
 *
 * Currently stubbed with mock responses. Wire up to your preferred API
 * by setting VITE_CONVERSION_API_URL.
 */

import type { ConversionPayload } from '@/components/ConversionDialog';

/* ─── Response types ────────────────────────────────────── */

export interface ConversionResult {
  success: boolean;
  code: string;
  framework: string;
  preview?: string; // rendered HTML preview
  error?: string;
}

export interface GenerationPayload {
  prompt: string;
  model: string;
  framework: 'react' | 'html' | 'tailwind';
  imageRefs?: string[];   // base64 data URIs of reference images
  libraryId?: string;
}

/* ─── API configuration ─────────────────────────────────── */

const API_BASE = import.meta.env.VITE_CONVERSION_API_URL || '';

/* ─── Prompt-based generation ───────────────────────────── */

export async function generateFromPrompt(
  payload: GenerationPayload,
): Promise<ConversionResult> {
  if (API_BASE) {
    try {
      const response = await fetch(`${API_BASE}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!response.ok) throw new Error(`API error: ${response.status}`);
      return await response.json();
    } catch (err) {
      return {
        success: false,
        code: '',
        framework: payload.framework,
        error: err instanceof Error ? err.message : 'Unknown error',
      };
    }
  }

  return mockGeneration(payload);
}

/* ─── Mock generation ───────────────────────────────────── */

async function mockGeneration(payload: GenerationPayload): Promise<ConversionResult> {
  await new Promise((r) => setTimeout(r, 1800));

  const desc = payload.prompt || 'a UI component';
  const hasImages = (payload.imageRefs?.length ?? 0) > 0;
  const prefix = hasImages ? `/* Generated from ${payload.imageRefs!.length} reference image(s) */\n` : '';

  return {
    success: true,
    framework: 'react',
    code: `${prefix}import React from 'react';

export function GeneratedUI() {
  return (
    <div className="flex flex-col gap-4 p-6 rounded-xl border border-gray-200 bg-white shadow-sm">
      <h2 className="text-xl font-semibold text-gray-900">${desc}</h2>
      <p className="text-sm text-gray-500">
        Generated by ${payload.model}${payload.libraryId ? ` using design system` : ''}
      </p>
      <div className="flex gap-2">
        <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
          Primary
        </button>
        <button className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition">
          Secondary
        </button>
      </div>
    </div>
  );
}`,
  };
}

/* ─── Main conversion function ──────────────────────────── */

export async function convertToUI(
  payload: ConversionPayload,
  imageData?: string, // base64 data URI of the sketch/image
): Promise<ConversionResult> {
  // If an API endpoint is configured, use it
  if (API_BASE) {
    return callRemoteAPI(payload, imageData);
  }

  // Otherwise return a mock response for development
  return mockConversion(payload);
}

/* ─── Remote API call ───────────────────────────────────── */

async function callRemoteAPI(
  payload: ConversionPayload,
  imageData?: string,
): Promise<ConversionResult> {
  try {
    const response = await fetch(`${API_BASE}/convert`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...payload,
        image: imageData,
      }),
    });

    if (!response.ok) {
      throw new Error(`API error: ${response.status}`);
    }

    return await response.json();
  } catch (err) {
    return {
      success: false,
      code: '',
      framework: payload.framework,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}

/* ─── Mock conversion for development ───────────────────── */

async function mockConversion(payload: ConversionPayload): Promise<ConversionResult> {
  // Simulate API latency
  await new Promise((r) => setTimeout(r, 1500));

  const { framework, fidelity, prompt } = payload;
  const desc = prompt || 'a UI component';

  if (framework === 'react') {
    return {
      success: true,
      framework: 'react',
      code: `import React from 'react';

export function GeneratedComponent() {
  return (
    <div className="p-6 rounded-lg border border-gray-200 bg-white shadow-sm">
      <h2 className="text-lg font-semibold mb-4">${desc}</h2>
      <p className="text-gray-600 mb-4">
        Generated from ${fidelity} conversion
      </p>
      <button className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
        Action
      </button>
    </div>
  );
}`,
    };
  }

  if (framework === 'tailwind') {
    return {
      success: true,
      framework: 'tailwind',
      code: `<div class="p-6 rounded-lg border border-gray-200 bg-white shadow-sm">
  <h2 class="text-lg font-semibold mb-4">${desc}</h2>
  <p class="text-gray-600 mb-4">
    Generated from ${fidelity} conversion
  </p>
  <button class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
    Action
  </button>
</div>`,
    };
  }

  return {
    success: true,
    framework: 'html',
    code: `<div style="padding: 24px; border-radius: 8px; border: 1px solid #e5e7eb; background: white; box-shadow: 0 1px 2px rgba(0,0,0,0.05);">
  <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">${desc}</h2>
  <p style="color: #6b7280; margin-bottom: 16px;">
    Generated from ${fidelity} conversion
  </p>
  <button style="padding: 8px 16px; background: #2563eb; color: white; border-radius: 6px; border: none; cursor: pointer;">
    Action
  </button>
</div>`,
  };
}
