import type { AdapterPack } from './types';

export const ADAPTER_PACKS: AdapterPack[] = [
  {
    id: 'material-ui-3',
    name: 'Material UI 3 Adapter',
    designSystem: 'Material UI 3',
    sourceUrl: 'https://github.com/mui/material-ui',
    storybookUrl: 'https://mui.com/material-ui/all-components/',
    docsUrl: 'https://mui.com/material-ui/',
    tokenDocsUrl: 'https://mui.com/material-ui/customization/default-theme/',
    supportedNodeTypes: [
      'container', 'stack', 'grid', 'section',
      'heading', 'text', 'paragraph', 'badge', 'avatar', 'icon',
      'button', 'input', 'textarea', 'select', 'checkbox', 'radio', 'toggle', 'slider',
      'navbar', 'sidebar', 'tabs', 'breadcrumb', 'menu', 'link',
      'card', 'table', 'list', 'listItem', 'stat', 'chart',
      'alert', 'toast', 'progress', 'dialog', 'tooltip', 'skeleton', 'spinner',
      'divider', 'scroll', 'image', 'code',
    ],
    density: 'comfortable',
    tokens: {
      fontFamily: 'Roboto, "Noto Sans", sans-serif',
      radiusSm: '8px',
      radiusMd: '12px',
      radiusLg: '16px',
      spacingBase: 8,
      borderWidth: '1px',
      focusRing: '0 0 0 2px rgba(103,80,164,0.25)',
      shadowCard: '0 1px 2px rgba(0,0,0,0.2), 0 1px 3px 1px rgba(0,0,0,0.14)',
    },
    variants: {
      buttonPrimary: 'filled',
      buttonSecondary: 'tonal',
      inputTone: 'outlined',
      cardTone: 'elevated',
    },
    componentRules: [
      {
        nodeType: 'button',
        defaultProps: { variant: 'primary' },
        defaultStyles: { borderRadius: '20px', minHeight: '40px', fontWeight: '500' },
      },
      {
        nodeType: 'input',
        defaultStyles: { borderRadius: '4px', minHeight: '40px', padding: '10px 14px' },
      },
      {
        nodeType: 'card',
        defaultStyles: { borderRadius: '12px', borderWidth: '0', boxShadow: '0 1px 2px rgba(0,0,0,0.2), 0 1px 3px 1px rgba(0,0,0,0.14)' },
      },
    ],
  },
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui Adapter',
    designSystem: 'shadcn/ui',
    sourceUrl: 'https://github.com/shadcn-ui/ui',
    storybookUrl: 'https://ui.shadcn.com/docs/components',
    docsUrl: 'https://ui.shadcn.com/docs',
    tokenDocsUrl: 'https://ui.shadcn.com/docs/theming',
    supportedNodeTypes: [
      'container', 'stack', 'grid', 'section',
      'heading', 'text', 'paragraph', 'badge', 'avatar', 'icon', 'code',
      'button', 'input', 'textarea', 'select', 'checkbox', 'radio', 'toggle', 'slider',
      'navbar', 'sidebar', 'tabs', 'breadcrumb', 'menu', 'link',
      'card', 'table', 'list', 'listItem', 'stat', 'chart',
      'alert', 'toast', 'progress', 'dialog', 'tooltip', 'skeleton', 'spinner',
      'divider', 'scroll', 'image',
    ],
    density: 'compact',
    tokens: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, sans-serif',
      radiusSm: '6px',
      radiusMd: '8px',
      radiusLg: '10px',
      spacingBase: 6,
      borderWidth: '1px',
      focusRing: '0 0 0 2px rgba(161,161,170,0.16)',
      shadowCard: 'none',
    },
    variants: {
      buttonPrimary: 'default',
      buttonSecondary: 'secondary',
      inputTone: 'subtle',
      cardTone: 'surface',
    },
    componentRules: [
      {
        nodeType: 'button',
        defaultProps: { variant: 'primary' },
        defaultStyles: { borderRadius: '8px', minHeight: '36px', fontWeight: '500', letterSpacing: '-0.006em' },
      },
      {
        nodeType: 'input',
        defaultStyles: { borderRadius: '6px', minHeight: '36px', padding: '8px 12px' },
      },
      {
        nodeType: 'card',
        defaultStyles: { borderRadius: '8px', borderWidth: '1px', boxShadow: 'none' },
      },
    ],
  },
  {
    id: 'ant-design',
    name: 'Ant Design Adapter',
    designSystem: 'Ant Design',
    sourceUrl: 'https://github.com/ant-design/ant-design',
    storybookUrl: 'https://ant.design/components/overview/',
    docsUrl: 'https://ant.design/docs/react/introduce',
    tokenDocsUrl: 'https://ant.design/docs/react/customize-theme',
    supportedNodeTypes: [
      'container', 'stack', 'grid', 'section', 'heading', 'text', 'paragraph', 'badge', 'avatar',
      'button', 'input', 'textarea', 'select', 'checkbox', 'radio', 'toggle', 'slider',
      'navbar', 'sidebar', 'tabs', 'breadcrumb', 'menu', 'link', 'card', 'table', 'list', 'listItem', 'stat',
      'alert', 'toast', 'progress', 'dialog', 'tooltip', 'skeleton', 'spinner', 'divider', 'scroll', 'image', 'icon', 'code', 'chart',
    ],
    density: 'compact',
    tokens: {
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      radiusSm: '4px',
      radiusMd: '6px',
      radiusLg: '8px',
      spacingBase: 4,
      borderWidth: '1px',
      focusRing: '0 0 0 2px rgba(22,119,255,0.1)',
      shadowCard: '0 1px 2px rgba(0,0,0,0.05)',
    },
    variants: {
      buttonPrimary: 'solid',
      buttonSecondary: 'default',
      inputTone: 'outlined',
      cardTone: 'outlined',
    },
    componentRules: [],
  },
  {
    id: 'fluent-ui',
    name: 'Fluent UI Adapter',
    designSystem: 'Fluent UI',
    sourceUrl: 'https://github.com/microsoft/fluentui',
    storybookUrl: 'https://react.fluentui.dev/?path=/docs/concepts-introduction--docs',
    docsUrl: 'https://react.fluentui.dev/',
    tokenDocsUrl: 'https://react.fluentui.dev/?path=/docs/concepts-theming--docs',
    supportedNodeTypes: [
      'container', 'stack', 'grid', 'section', 'heading', 'text', 'paragraph', 'badge', 'avatar',
      'button', 'input', 'textarea', 'select', 'checkbox', 'radio', 'toggle', 'slider',
      'navbar', 'sidebar', 'tabs', 'breadcrumb', 'menu', 'link', 'card', 'table', 'list', 'listItem', 'stat',
      'alert', 'toast', 'progress', 'dialog', 'tooltip', 'skeleton', 'spinner', 'divider', 'scroll', 'image', 'icon', 'code', 'chart',
    ],
    density: 'comfortable',
    tokens: {
      fontFamily: '"Segoe UI", "Segoe UI Web", -apple-system, sans-serif',
      radiusSm: '4px',
      radiusMd: '6px',
      radiusLg: '8px',
      spacingBase: 8,
      borderWidth: '1px',
      focusRing: '0 0 0 2px rgba(0,120,212,0.22)',
      shadowCard: '0 2px 4px rgba(0,0,0,0.04)',
    },
    variants: {
      buttonPrimary: 'brand',
      buttonSecondary: 'subtle',
      inputTone: 'filled',
      cardTone: 'filled',
    },
    componentRules: [],
  },
  {
    id: 'radix-ui',
    name: 'Radix UI Adapter',
    designSystem: 'Radix UI',
    sourceUrl: 'https://github.com/radix-ui/primitives',
    storybookUrl: 'https://www.radix-ui.com/primitives/docs/components',
    docsUrl: 'https://www.radix-ui.com/primitives/docs/overview/introduction',
    tokenDocsUrl: 'https://www.radix-ui.com/themes/docs/theme/tokens',
    supportedNodeTypes: [
      'container', 'stack', 'grid', 'section', 'heading', 'text', 'paragraph', 'badge', 'avatar',
      'button', 'input', 'textarea', 'select', 'checkbox', 'radio', 'toggle', 'slider',
      'navbar', 'sidebar', 'tabs', 'breadcrumb', 'menu', 'link', 'card', 'table', 'list', 'listItem', 'stat',
      'alert', 'toast', 'progress', 'dialog', 'tooltip', 'skeleton', 'spinner', 'divider', 'scroll', 'image', 'icon', 'code', 'chart',
    ],
    density: 'compact',
    tokens: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, sans-serif',
      radiusSm: '6px',
      radiusMd: '8px',
      radiusLg: '10px',
      spacingBase: 8,
      borderWidth: '1px',
      focusRing: '0 0 0 1px #3e63dd',
      shadowCard: 'none',
    },
    variants: {
      buttonPrimary: 'solid',
      buttonSecondary: 'soft',
      inputTone: 'surface',
      cardTone: 'surface',
    },
    componentRules: [],
  },
];
